development:
  adapter: postgresql
  encoding: utf8
  database: everyway_development
  pool: 5
  username: everyway
  password: password1

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: everyway_test
  pool: 5
  username: everyway
  password: password1

production:
  adapter: postgresql
  encoding: utf8
  database: everyway_production
  pool: 5
  username: 
  password:

